runtime: php72

automatic_scaling:
 max_instances: 1

handlers:

#- url: /assets/img/(.*\.(bmp|gif|ico|jpeg|jpg|png))
#  static_files: img/\1
#  upload: public/assets/img/(.*\.(bmp|gif|ico|jpeg|jpg|png))
#
#- url: /assets/css/(.*\.css)
#  static_files: css/\1
#  upload: public/assets/css/(.*\.css)
#
#- url: /assets/fonts/(.*\.(md|eot|ttf|woff|woffw))
#  static_files: fonts/\1
#  upload: public/assets/fonts/(.*\.(md|eot|ttf|woff|woffw))
#
#- url: /assets/js/(.*\.(js))
#  static_files: js/\1
#  upload: public/assets/js/(.*\.(js))

- url: .*
  script: auto

includes:
- gae/secret.yaml
