app:
  image: busybox
  volumes:
    - ../:/var/www/html/teamleague.com
    - ./var/log:/var/log
  tty: true
php:
  build: ./php
  env_file: ../environment/production/.env
  links:
    - mysql
  volumes_from:
    - app
nginx:
  build: ./nginx
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app
mysql:
  build: ./mysql
  env_file: ../environment/production/.env
  ports:
    - 3306:3306
  environment:
    - "TZ=Asia/Tokyo"
  volumes:
    - ../.mysql:/var/lib/mysql
  volumes_from:
    - app
#phpmyadmin:
#  image: phpmyadmin/phpmyadmin
#  env_file: ../environment/production/.env
#  links:
#    - mysql
#  ports:
#     - 8080:80
#  volumes:
#     - ./phpmyadmin/sessions:/sessions
