app:
  image: busybox
  volumes:
    - ../:/var/www/html/teamleague.com
    - ./var/log:/var/log
    - ../secret/:/var/www/html/teamleague.com/secret
  tty: true
php:
  build: ./php
  env_file: ../environment/development/.env
  links:
    - mysql
  volumes_from:
    - app
nginx:
  build: ./nginx
  ports: 
    - 12000:80
  links:
    - php
  volumes_from:
    - app
mysql:
  build: ./mysql
  env_file: ../environment/development/.env
  ports:
    - 12001:3306
  environment:
    - "TZ=Asia/Tokyo"
  volumes:
    - ../.mysql:/var/lib/mysql
  volumes_from:
    - app
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  env_file: ../environment/development/.env
  links:
    - mysql
  ports:
     - 12002:80
  volumes:
     - ./phpmyadmin/sessions:/sessions
